altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  2b79723f-475c-411f-97df-ed4536442c61:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: e9cf1fcd-70fa-46e9-b133-331545b797ea
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 87520abf-3373-4e15-b94c-05caa91edc15
        userCondition: null
fs: uploads
handle: uploads
name: Uploads
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: uploads
transformSubpath: ''
