dateModified: 1715673583
email:
  fromEmail: vipinvarghese5656@gmail.com
  fromName: eventsite
  transportType: craft\mail\transportadapters\Sendmail
fs:
  uploads:
    hasUrls: true
    name: Uploads
    settings:
      path: $ASSET_BASE_PATH
    type: craft\fs\Local
    url: $ASSET_BASE_URL
meta:
  __names__:
    55f02652-e9b7-4bed-a876-878a7252c8d2: 'Hero title' # Hero title
    692f0414-fee9-43f6-a6f3-05148fd8c84d: eventsite # eventsite
    e4487530-3eb3-4458-9110-a144be9e2342: Uploads # Uploads
    f7fb0bf2-f2ec-47e1-ab5e-6f187ea36cc1: eventsite # eventsite
system:
  edition: solo
  live: true
  name: eventsite
  schemaVersion: 5.0.0.20
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
